export default [
  { img: "", text: "Les Personnes" },
  { img: "family.svg", text: "Groupe - Famille" },
  { img: "female.svg", text: "Féminin" },
  { img: "male.svg", text: "Masculin" },
  { img: "genderfree.svg", text: "GenderFree" },
  { img: "children.svg", text: "Jeune" },
  { img: "old.svg", text: "Vieux" },

  { img: "", text: "Les catégories" },
  { img: "tshirt.svg", text: "Vêtements" },
  { img: "Food.svg", text: "Nourriture" },
  { img: "tools.svg", text: "Outils" },
  { img: "Fly.svg", text: "Avion" },
  { img: "boat.svg", text: "Bateau" },
  { img: "object.svg", text: "Objet" },
  { img: "jobs.svg", text: "Métiers" },
  { img: "loisirSport.svg", text: "Loisir - Sport - Activité" },
  { img: "idea.svg", text: "Idée - Pensée" },
  { img: "speech.svg", text: "Citation - Expression" },
  { img: "arts.svg", text: "Arts" },
  { img: "calendar.svg", text: "Date" },
  { img: "city.svg", text: "Ville" },
  { img: "litterature.svg", text: "Litterature" },
  { img: "music.svg", text: "Musique" },
  { img: "movie.svg", text: "Cinéma" },
  { img: "tv.svg", text: "Télévision" },
  { img: "house.svg", text: "Maison - Domestique" },

  { img: "", text: "Le Corps" },
  { img: "arm.svg", text: "Bras - Main" },
  { img: "torso.svg", text: "Torse" },
  { img: "head.svg", text: "Tête" },
  { img: "mouth.svg", text: "Bouche - Goût" },
  { img: "hear.svg", text: "Oreille - Entendre" },
  { img: "see.svg", text: "Oeil - Voir" },
  { img: "leg.svg", text: "Jambe - Pied" },

  { img: "", text: "La société" },
  { img: "power.svg", text: "Politique" },
  { img: "war.svg", text: "Conflit - Guerre" },
  { img: "defense.svg", text: "Defense" },
  { img: "meca.svg", text: "Mécanique" },
  { img: "electronic.svg", text: "Electronique" },
  { img: "love.svg", text: "Amour" },
  { img: "death.svg", text: "Mort" },
  { img: "happy.svg", text: "Content" },
  { img: "sad.svg", text: "Triste" },
  { img: "religion.svg", text: "Religieux - Mythique" },
  { img: "time.svg", text: "Time" },
  { img: "money.svg", text: "Money" },
  { img: "science.svg", text: "Science" },

  { img: "", text: "Les couleurs" },
  { img: "color-black.svg", text: "Noir" },
  { img: "color-blue.svg", text: "Bleu" },
  { img: "color-brown.svg", text: "Marron" },
  { img: "color-green.svg", text: "Vert" },
  { img: "color-orange.svg", text: "Orange" },
  { img: "color-pink.svg", text: "Rose" },
  { img: "color-purple.svg", text: "Violet" },
  { img: "color-red.svg", text: "Rouge" },
  { img: "color-transparent.svg", text: "Transparent" },
  { img: "color-white.svg", text: "Blanc" },
  { img: "color-yellow.svg", text: "Jaune" },

  { img: "", text: "Les formes" },
  { img: "triangle.svg", text: "Triangle" },
  { img: "cone.svg", text: "Cone" },
  { img: "flat.svg", text: "Plat" },
  { img: "cube.svg", text: "Cube" },
  { img: "cylinder.svg", text: "Cylindre" },
  { img: "square.svg", text: "Carré" },
  { img: "pyramid.svg", text: "Pyramide" },
  { img: "circle.svg", text: "Cercle" },
  { img: "sphere.svg", text: "Sphere" },
  { img: "line.svg", text: "Trait - Ligne" },
  { img: "star.svg", text: "Etoile" },
  { img: "emptycircle.svg", text: "Cercle vide" },

  { img: "", text: "La météo" },
  { img: "day.svg", text: "Jour - Soleil" },
  { img: "night.svg", text: "Nuit" },
  { img: "storm.svg", text: "Orage" },
  { img: "hot.svg", text: "Chaud" },
  { img: "cold.svg", text: "Froid" },

  { img: "", text: "Les éléments" },
  { img: "rock.svg", text: "Pierre" },
  { img: "soil.svg", text: "Terre" },
  { img: "wind.svg", text: "Vent" },
  { img: "fire.svg", text: "Feu" },
  { img: "water.svg", text: "Water" },

  { img: "", text: "Les matières" },
  { img: "paper.svg", text: "Papier" },
  { img: "plastic.svg", text: "Platique" },
  { img: "wood.svg", text: "Bois" },
  { img: "steel.svg", text: "Acier" },
  { img: "fabric.svg", text: "Tissu" },

  { img: "", text: "" },
  { img: "grid.svg", text: "Réseau" },
  { img: "hole.svg", text: "Trou - Vide" },
  { img: "inside.svg", text: "Intérieur" },
  { img: "press.svg", text: "Action - Verbe" },
  { img: "puzzle.svg", text: "Pièce - Morceau" },
  { img: "rabbit.svg", text: "Rapide" },
  { img: "slow.svg", text: "Lent" },
];
