import uuid from "react-uuid";

export default [
  { id: uuid(), img: "", text: "Les Personnes" },
  { id: uuid(), img: "family.svg", text: "Famille - Société - Groupe" },
  { id: uuid(), img: "female.svg", text: "Femme - Féminin - Femelle" },
  { id: uuid(), img: "male.svg", text: "Homme - Masculin - Mâle" },
  { id: uuid(), img: "genderfree.svg", text: "GenderFree" },
  { id: uuid(), img: "children.svg", text: "Jeune - Nouveau - Enfant - Bébé" },
  { id: uuid(), img: "old.svg", text: "Vieux - Ancien - Passé" },

  { id: uuid(), img: "", text: "Les catégories" },
  { id: uuid(), img: "fauna.svg", text: "Faune - Animal" },
  { id: uuid(), img: "nature.svg", text: "Flore - Plante" },
  { id: uuid(), img: "location.svg", text: "Lieu - Pays - Drapeau" },
  { id: uuid(), img: "tshirt.svg", text: "Vêtements - Accessoires - Costumes" },
  { id: uuid(), img: "Food.svg", text: "Nourriture" },
  { id: uuid(), img: "tools.svg", text: "Outils" },
  { id: uuid(), img: "Fly.svg", text: "Véhicule volant - Aérien - Voler" },
  {
    id: uuid(),
    img: "transportation.svg",
    text: "Véhicule routier - Voiture - Rouler",
  },
  { id: uuid(), img: "boat.svg", text: "Véhicule Marine - Maritime - Nager" },
  { id: uuid(), img: "object.svg", text: "Objet - Paquet - Carton" },
  { id: uuid(), img: "kid-and-baby.svg", text: "Jeux - Jouet" },
  { id: uuid(), img: "jobs.svg", text: "Travail - Métier" },
  { id: uuid(), img: "loisirSport.svg", text: "Loisir - Sport - Activité" },
  { id: uuid(), img: "idea.svg", text: "Idée - Pensée" },
  {
    id: uuid(),
    img: "speech.svg",
    text: "Expression - Langue - Dialogue - Bande dessinée",
  },
  { id: uuid(), img: "arts.svg", text: "Arts" },
  { id: uuid(), img: "calendar.svg", text: "Date - Evènement - Jour" },
  { id: uuid(), img: "shapes.svg", text: "Fêtes - Anniversaires" },
  { id: uuid(), img: "city.svg", text: "Bâtiment - Construction - Ville" },
  {
    id: uuid(),
    img: "litterature.svg",
    text: "Littérature - Ecriture - Livre",
  },
  { id: uuid(), img: "music.svg", text: "Musique - Chanson - Note" },
  { id: uuid(), img: "movie.svg", text: "Cinéma - Film" },
  { id: uuid(), img: "tv.svg", text: "Télévision" },
  { id: uuid(), img: "house.svg", text: "Maison - Domestique" },

  { id: uuid(), img: "", text: "Le Corps" },
  { id: uuid(), img: "arm.svg", text: "Bras - Main" },
  { id: uuid(), img: "torso.svg", text: "Torse - Ventre - Corps" },
  { id: uuid(), img: "head.svg", text: "Tête - Visage" },
  { id: uuid(), img: "leg.svg", text: "Jambe - Pied" },
  { id: uuid(), img: "mouth.svg", text: "Bouche - Goût - Manger" },
  { id: uuid(), img: "hear.svg", text: "Oreille - Son - Entendre" },
  { id: uuid(), img: "see.svg", text: "Oeil - Vue - Voir" },
  { id: uuid(), img: "body-parts.svg", text: "Nez - Odorat - Sentir" },

  { id: uuid(), img: "", text: "La société" },
  { id: uuid(), img: "power.svg", text: "Pouvoir - Politique" },
  { id: uuid(), img: "war.svg", text: "Conflit - Arme - Combattre" },
  { id: uuid(), img: "defense.svg", text: "Défense - Protection - Mur" },
  { id: uuid(), img: "meca.svg", text: "Mécanique" },
  { id: uuid(), img: "electronic.svg", text: "Electronique - Informatique" },
  { id: uuid(), img: "love.svg", text: "Vie - Coeur - Amour" },
  { id: uuid(), img: "death.svg", text: "Mort - Mal - Maladie" },
  { id: uuid(), img: "happy.svg", text: "Joyeux - Positif" },
  { id: uuid(), img: "sad.svg", text: "Triste - Négatif" },
  { id: uuid(), img: "religion.svg", text: "Religieux - Mythique" },
  { id: uuid(), img: "time.svg", text: "Time" },
  { id: uuid(), img: "money.svg", text: "Money" },
  { id: uuid(), img: "science.svg", text: "Sciences - Maths - Chimie" },
  {
    id: uuid(),
    img: "healthcare-and-medical.svg",
    text: "Médical - Médicament - Soigner",
  },

  { id: uuid(), img: "", text: "Les couleurs" },
  { id: uuid(), img: "color-black.svg", text: "Noir" },
  { id: uuid(), img: "color-blue.svg", text: "Bleu" },
  { id: uuid(), img: "color-brown.svg", text: "Marron" },
  { id: uuid(), img: "color-green.svg", text: "Vert" },
  { id: uuid(), img: "color-orange.svg", text: "Orange" },
  { id: uuid(), img: "color-pink.svg", text: "Rose" },
  { id: uuid(), img: "color-purple.svg", text: "Violet" },
  { id: uuid(), img: "color-red.svg", text: "Rouge" },
  { id: uuid(), img: "color-transparent.svg", text: "Blanc" },
  { id: uuid(), img: "color-white.svg", text: "Transparent" },
  { id: uuid(), img: "color-yellow.svg", text: "Jaune" },

  { id: uuid(), img: "", text: "Les formes" },
  { id: uuid(), img: "triangle.svg", text: "Triangle" },
  { id: uuid(), img: "cone.svg", text: "Cone" },
  { id: uuid(), img: "flat.svg", text: "Plat" },
  { id: uuid(), img: "cube.svg", text: "Cube" },
  { id: uuid(), img: "cylinder.svg", text: "Cylindre" },
  { id: uuid(), img: "square.svg", text: "Carré" },
  { id: uuid(), img: "pyramid.svg", text: "Pyramide" },
  { id: uuid(), img: "circle.svg", text: "Cercle" },
  { id: uuid(), img: "sphere.svg", text: "Sphere" },
  { id: uuid(), img: "emptycircle.svg", text: "Cercle - Anneau" },
  { id: uuid(), img: "star.svg", text: "Etoile" },
  { id: uuid(), img: "line.svg", text: "Ligne - Droit" },
  { id: uuid(), img: "cross.svg", text: "Croix - Croisement" },
  { id: uuid(), img: "arc.svg", text: "Arc - Courbé - Bombé" },
  { id: uuid(), img: "spiral.svg", text: "Spirale - Ivresse - Folie - Poil" },
  {
    id: uuid(),
    img: "swirl.svg",
    text: "Sinusoïdale - Ondulation - Cheveux - Rivière",
  },
  {
    id: uuid(),
    img: "mountain.svg",
    text: "Ligne brisée - Pointu - Accidenté",
  },

  { id: uuid(), img: "", text: "La météo" },
  { id: uuid(), img: "day.svg", text: "Soleil - Lumière - Jour" },
  { id: uuid(), img: "night.svg", text: "Nuit - Soir - Lune" },
  { id: uuid(), img: "meteorology.svg", text: "Pluie - Neige" },
  { id: uuid(), img: "storm.svg", text: "Eclair - Electricité - Tempête" },
  { id: uuid(), img: "hot.svg", text: "Chaud" },
  { id: uuid(), img: "cold.svg", text: "Froid" },

  { id: uuid(), img: "", text: "Les matières" },
  { id: uuid(), img: "rock.svg", text: "Roche - Minéral - Dur" },
  { id: uuid(), img: "soil.svg", text: "Terre" },
  { id: uuid(), img: "wind.svg", text: "Air - Vent - Souffler" },
  { id: uuid(), img: "fire.svg", text: "Feu - Brûler" },
  { id: uuid(), img: "water.svg", text: "Eau - Liquide - Aquatique" },
  { id: uuid(), img: "paper.svg", text: "Papier - Feuille" },
  { id: uuid(), img: "plastic.svg", text: "Platique - Caoutchouc" },
  { id: uuid(), img: "wood.svg", text: "Bois" },
  { id: uuid(), img: "steel.svg", text: "Métal" },
  { id: uuid(), img: "fabric.svg", text: "Tissu" },

  { id: uuid(), img: "", text: "Les qualités" },
  { id: uuid(), img: "grid.svg", text: "Grille - Réseau - Prison" },
  { id: uuid(), img: "opposed.svg", text: "Opposé - Contraire - Inverse" },
  { id: uuid(), img: "cut.svg", text: "Couper - Séparer - Moitié" },
  { id: uuid(), img: "puzzle.svg", text: "Partie de - Pièce de - Morceau de" },
  { id: uuid(), img: "particle.svg", text: "Fragment - Multitude - Poudre" },
  { id: uuid(), img: "inside.svg", text: "Dedans - Interne" },
  { id: uuid(), img: "hole.svg", text: "Creu - Trou - Percé - Vide" },
  { id: uuid(), img: "rabbit.svg", text: "Rapide - Vif" },
  { id: uuid(), img: "slow.svg", text: "Lent" },
  { id: uuid(), img: "press.svg", text: "Action - Verbe" },
  { id: uuid(), img: "tall.svg", text: "Grand - Plus grand - Plus haut" },
  { id: uuid(), img: "small.svg", text: "Petit - Plus petit - Plus bas" },
  { id: uuid(), img: "large.svg", text: "Gros - Large - Plus long" },
  {
    id: uuid(),
    img: "thin.svg",
    text: "Mince - Fin - Plus étroit - Plus court",
  },
  { id: uuid(), img: "up.svg", text: "Haut - Monter" },
  { id: uuid(), img: "down.svg", text: "Bas - Descendre" },
  { id: uuid(), img: "right.svg", text: "Droite - Fin - Après" },
  { id: uuid(), img: "left.svg", text: "Gauche - Début - Avant" },
  { id: uuid(), img: "cycle.svg", text: "Tourner - Entourer - Cycle" },

  { id: uuid(), img: "", text: "La quantité" },
  { id: uuid(), img: "zero.svg", text: "Aucun - Zéro" },
  { id: uuid(), img: "one.svg", text: "Unité - Un" },
  { id: uuid(), img: "abit.svg", text: "Un peu" },
  { id: uuid(), img: "lot.svg", text: "Beaucoup" },
  { id: uuid(), img: "infinite.svg", text: "Infini - Enormément" },
];
